//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middlename { get; set; }
        public string Passport { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Company { get; set; }
        public string Jobname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }


        public string ImagePath
        {
            get { return "../photo/" + Photo.ToString(); }
        }
    }
}
